### ISSUE TITLE
Popup when creating a post with no category selected

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#2]
If you make a post and select no category, you'll get a popup but the post will still be created.

Repro:
1. Go to */admin/categories* and make sure there's at least one category created
2. Go to */admin/create/post* and make a post
3. **DO NOT** check any categories
4. Click Save post
5. Observe the following popup: **Something went wrong. Please Try again later...**
6. Go to */admin/posts* and see the post has been created.

**Comment by silencesys** [comment]
In latest release is category required for posting a post and post can't be posted without category selection, all errors are shown in post footer.
