### ISSUE TITLE
Post text editor doesn't support CTRL+A

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#3]
CTRL+A doesn't work with the Post text editor, Shift+Home and Shift+End still work fine

**Comment by YasRavenheart** [comment]
Portfolio description has the same editor but that one supports CTRL+A

**Comment by silencesys** [comment]
For me it's work, are you sure?

**Comment by silencesys** [comment]
Seems it's working from last update of medium editor. Closing this issue, thanks for report! :tea:
