### ISSUE TITLE
Cannot delete menu links

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#5]
Menu links cannot be deleted. Attempting to delete throws "_Use of undefined constant CAN_VIEW_POST - assumed 'CAN_VIEW_POST_'"

**Repro**:
1. Go to Settings -> Menu in Admin
2. Create a new link
3. Try to delete the link
4. Observe the error mentioned above

**Tested on**:
Google Chrome 42.0.2311.152 m

**Comment by silencesys** [comment]
Fixed in 254b21faccf74986ca6c8cddc8a9ba5c79da7ed8.
Because of changes in authorization there was a forgotten function to check user rights based on different requirements.
