### ISSUE TITLE
Saving edited menu link doesn't redirect correctly

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#7]
Editing and saving a menu link in settings doesn't redirect back to /admin/settings/menu. This makes it unable to create new links without going back manually after saving.

**Repro**:
1. Go to Settings -> Menu in Admin
2. Create a new link
3. Edit the newly created link
4. Save the edit, observe you get redirected back to /admin/settings/menu/edit-item/* and not /admin/settings/menu

**Comment by silencesys** [comment]
In latest release is redirect changed to menu index. :)
