### ISSUE TITLE
A post in Concept or Correction state can be visited

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#9]
A post that has its Status set to Concept or Correction is correctly not listed on the Home page but still can be visited via URL.

**Repro:**
1. Go to Admin -> Posts -> Create post
2. Create a post there, remember the slug
3. Set the status to Concept or Correction
4. Save the post and go to - domain.com/post/slug
5. Observe the post is still visible, this can be reproduced even when logged out of CMS

**Comment by silencesys** [comment]
Working on it. Now is post invisible, but your idea about post visibility for logged users with permission is very good. :+1:

**Comment by silencesys** [comment]
Preview function was added in latest version. :)
